#!/usr/bin/env python3
"""
Boolean Network Path to Attractor Tool
Simulates trajectories from initial states to attractors in Boolean networks.
Part of the Boolean Network Inference (BNI) pipeline.
"""

import argparse
import os
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import ListedColormap
from pathlib import Path
from matplotlib.patches import Rectangle


def log_message(message, verbose):
    """Print message only if verbose is enabled"""
    if verbose:
        print(message)


def read_attractors_file(attractors_file, verbose):
    """
    Read the attractors TSV file generated by 1.BNI3_Attractors.py
    
    Args:
        attractors_file (str): Path to the attractors TSV file
        verbose (bool): Enable verbose output
        
    Returns:
        tuple: (DataFrame, list of gene names, dict of attractors)
    """
    try:
        log_message(f"Reading attractors file: {attractors_file}", verbose)
        
        df = pd.read_csv(attractors_file, sep='\t')
        log_message(f"Loaded {len(df)} attractor states", verbose)
        
        # Extract gene names
        metadata_cols = ['attractor_id', 'type', 'cycle_length', 'step_in_cycle', 'binary_state', 'basin_size', 'basin_percentage']
        gene_cols = [col for col in df.columns if col not in metadata_cols]
        
        # Convert attractors to dictionary format for easy lookup
        attractors_dict = {}
        for att_id in df['attractor_id'].unique():
            att_data = df[df['attractor_id'] == att_id].sort_values('step_in_cycle')
            attractor_states = []
            for _, row in att_data.iterrows():
                state = [bool(row[gene]) for gene in gene_cols]
                attractor_states.append(state)
            
            attractors_dict[att_id] = {
                'states': attractor_states,
                'type': att_data.iloc[0]['type'],
                'cycle_length': att_data.iloc[0]['cycle_length'],
                'basin_size': att_data.iloc[0]['basin_size'],
                'basin_percentage': att_data.iloc[0]['basin_percentage']
            }
        
        log_message(f"Found {len(gene_cols)} genes and {len(attractors_dict)} attractors", verbose)
        return df, gene_cols, attractors_dict
        
    except Exception as e:
        raise ValueError(f"Error reading attractors file: {str(e)}")


def read_rules_file(rules_file, verbose):
    """
    Read rules from either a full rules table or a selected rules file
    
    Args:
        rules_file (str): Path to rules file (full table or selected rules)
        verbose (bool): Enable verbose output
        
    Returns:
        dict: Dictionary of selected rules per gene
    """
    try:
        log_message(f"Reading rules from: {rules_file}", verbose)
        
        if rules_file.endswith('.tsv'):
            df = pd.read_csv(rules_file, sep='\t', encoding='utf-8')
        else:
            df = pd.read_csv(rules_file, encoding='utf-8')
        
        # Check if it's a selected rules file (only Gene and Rule columns)
        if 'Position' in df.columns:
            # Full rules table - use same logic as before
            log_message("Detected full rules table, applying selection criteria", verbose)
            return read_full_rules_table(df, verbose)
        else:
            # Selected rules file - direct mapping
            log_message("Detected selected rules file, reading directly", verbose)
            selected_rules = {}
            for _, row in df.iterrows():
                gene = str(row['Gene'])
                rule = str(row['Rule'])
                selected_rules[gene] = rule
            
            log_message(f"Loaded {len(selected_rules)} pre-selected rules", verbose)
            return selected_rules
        
    except Exception as e:
        raise ValueError(f"Error reading rules file: {str(e)}")


def read_full_rules_table(df, verbose):
    """
    Read and select rules from full rules table (legacy functionality)
    """
    # Simple rule selection - just take Position=1 or minimum available
    selected_rules = {}
    genes = sorted(df['Gene'].unique())
    
    for gene in genes:
        gene_rules = df[df['Gene'] == gene].copy()
        
        # Try Position=1 first, otherwise take minimum position
        top_rules = gene_rules[gene_rules['Position'] == 1]
        if top_rules.empty:
            selected_rule = gene_rules.loc[gene_rules['Position'].idxmin()]
            log_message(f"Warning: No Position=1 found for {gene}, using Position={selected_rule['Position']}", verbose)
        else:
            selected_rule = top_rules.iloc[0]
        
        selected_rules[gene] = str(selected_rule['Rule'])
    
    log_message(f"Selected rules for {len(selected_rules)} genes from full table", verbose)
    return selected_rules


def parse_initial_state(initial_state_input, gene_cols, verbose):
    """
    Parse initial state from different input formats
    
    Args:
        initial_state_input (str): Initial state as binary string or gene list
        gene_cols (list): List of gene names
        verbose (bool): Enable verbose output
        
    Returns:
        list: Boolean state vector
    """
    log_message(f"Parsing initial state: {initial_state_input}", verbose)
    
    if initial_state_input.replace('0', '').replace('1', '') == '':
        # Binary string format
        if len(initial_state_input) != len(gene_cols):
            raise ValueError(f"Binary string length ({len(initial_state_input)}) must match number of genes ({len(gene_cols)})")
        state = [bool(int(bit)) for bit in initial_state_input]
    else:
        # Gene list format (comma-separated active genes)
        active_genes = [gene.strip() for gene in initial_state_input.split(',') if gene.strip()]
        state = [gene in active_genes for gene in gene_cols]
    
    active_genes = [gene_cols[i] for i, active in enumerate(state) if active]
    log_message(f"Initial state: {len(active_genes)} active genes: {', '.join(active_genes)}", verbose)
    
    return state


def evaluate_rule(rule, gene_state):
    """
    Evaluate a Boolean rule given a gene state
    
    Args:
        rule (str): Boolean rule string
        gene_state (dict): Dictionary mapping gene names to boolean values
        
    Returns:
        bool: Result of rule evaluation
    """
    rule_eval = rule.replace('&', ' and ').replace('|', ' or ').replace('~', ' not ')
    
    for gene, value in gene_state.items():
        rule_eval = rule_eval.replace(gene, str(value))
    
    try:
        result = eval(rule_eval)
        return bool(result)
    except:
        return False


def calculate_next_state(current_state, gene_rules, genes):
    """
    Calculate the next state of the network
    
    Args:
        current_state (list): Current state as list of booleans
        gene_rules (dict): Dictionary of gene rules
        genes (list): List of gene names in order
        
    Returns:
        list: Next state as list of booleans
    """
    next_state = {}
    
    for gene in genes:
        if gene in gene_rules:
            state_dict = {genes[i]: current_state[i] for i in range(len(genes))}
            next_state[gene] = evaluate_rule(gene_rules[gene], state_dict)
        else:
            idx = genes.index(gene)
            next_state[gene] = current_state[idx]
    
    return [next_state[gene] for gene in genes]


def state_to_string(state):
    """Convert state to binary string"""
    return ''.join(['1' if x else '0' for x in state])


def find_matching_attractor(current_state, attractors_dict):
    """
    Check if current state matches any known attractor
    
    Args:
        current_state (list): Current state
        attractors_dict (dict): Dictionary of known attractors
        
    Returns:
        tuple: (attractor_id, step_in_cycle) or (None, None)
    """
    current_state_str = state_to_string(current_state)
    
    for att_id, att_info in attractors_dict.items():
        for step, att_state in enumerate(att_info['states']):
            if state_to_string(att_state) == current_state_str:
                return att_id, step + 1
    
    return None, None


def simulate_trajectory_to_attractor(initial_state, gene_rules, genes, attractors_dict, max_steps=1000, verbose=False):
    """
    Simulate trajectory from initial state to attractor
    
    Args:
        initial_state (list): Initial state
        gene_rules (dict): Gene rules
        genes (list): Gene names
        attractors_dict (dict): Known attractors
        max_steps (int): Maximum simulation steps
        verbose (bool): Enable verbose output
        
    Returns:
        dict: Simulation results
    """
    log_message("Starting trajectory simulation...", verbose)
    
    trajectory = []
    current_state = initial_state[:]
    visited_states = set()
    
    # Check if initial state is already in an attractor
    att_id, step_in_cycle = find_matching_attractor(current_state, attractors_dict)
    if att_id is not None:
        log_message(f"Initial state is already in attractor {att_id}, step {step_in_cycle}", verbose)
        return {
            'target_attractor_id': att_id,
            'steps_to_attractor': 0,
            'trajectory': [current_state[:]],
            'converged': True,
            'found_at_step': step_in_cycle
        }
    
    for step in range(max_steps):
        trajectory.append(current_state[:])
        state_str = state_to_string(current_state)
        
        # Check if we've entered a known attractor
        att_id, step_in_cycle = find_matching_attractor(current_state, attractors_dict)
        if att_id is not None:
            log_message(f"Reached attractor {att_id} at step {step + 1}", verbose)
            return {
                'target_attractor_id': att_id,
                'steps_to_attractor': step + 1,
                'trajectory': trajectory,
                'converged': True,
                'found_at_step': step_in_cycle
            }
        
        # Check for cycles not in known attractors
        if state_str in visited_states:
            log_message(f"Entered unknown cycle at step {step + 1}", verbose)
            return {
                'target_attractor_id': None,
                'steps_to_attractor': step + 1,
                'trajectory': trajectory,
                'converged': False,
                'found_at_step': None
            }
        
        visited_states.add(state_str)
        current_state = calculate_next_state(current_state, gene_rules, genes)
    
    log_message(f"Simulation did not converge within {max_steps} steps", verbose)
    return {
        'target_attractor_id': None,
        'steps_to_attractor': max_steps,
        'trajectory': trajectory,
        'converged': False,
        'found_at_step': None
    }


def save_trajectory_tsv(trajectory, genes, result, output_path, filename, verbose=False):
    """
    Save trajectory to TSV file
    
    Args:
        trajectory (list): List of states in trajectory
        genes (list): Gene names
        result (dict): Simulation results
        output_path (str): Output directory
        filename (str): Output filename
        verbose (bool): Enable verbose output
    """
    trajectory_data = []
    
    for step, state in enumerate(trajectory):
        row = {
            'step': step,
            'binary_state': state_to_string(state)
        }
        
        # Add state of each gene
        for i, gene in enumerate(genes):
            row[gene] = int(state[i])
        
        # Add metadata
        if step == 0:
            row['phase'] = 'initial'
        elif step == len(trajectory) - 1 and result['converged']:
            row['phase'] = 'attractor_reached'
        else:
            row['phase'] = 'transient'
        
        trajectory_data.append(row)
    
    # Add summary information as comments at the top
    df = pd.DataFrame(trajectory_data)
    full_path = os.path.join(output_path, filename)
    
    with open(full_path, 'w') as f:
        f.write(f"# Trajectory simulation results\n")
        f.write(f"# Target attractor: {result['target_attractor_id']}\n")
        f.write(f"# Steps to attractor: {result['steps_to_attractor']}\n")
        f.write(f"# Converged: {result['converged']}\n")
        if result['found_at_step']:
            f.write(f"# Found at step in cycle: {result['found_at_step']}\n")
        f.write(f"# Total trajectory length: {len(trajectory)}\n")
        f.write(f"#\n")
        
        # Write the dataframe
        df.to_csv(f, sep='\t', index=False)
    
    log_message(f"Trajectory saved to: {filename}", verbose)
    return df


def visualize_trajectory(trajectory, genes, result, attractors_dict, output_path, verbose=False):
    """
    Create visualization of the trajectory
    
    Args:
        trajectory (list): List of states
        genes (list): Gene names
        result (dict): Simulation results
        attractors_dict (dict): Known attractors
        output_path (str): Output file path (without extension)
        verbose (bool): Enable verbose output
    """
    log_message("Creating trajectory visualization...", verbose)
    
    n_genes = len(genes)
    n_steps = len(trajectory)
    
    # Create figure
    fig_width = max(10, min(20, n_steps * 0.3 + 4))
    fig_height = max(6, min(12, n_genes * 0.4 + 3))
    
    fig, ax1 = plt.subplots(1, 1, figsize=(fig_width, fig_height))
    
    # Prepare data for heatmap
    trajectory_matrix = np.array([[int(state[i]) for i in range(n_genes)] for state in trajectory])
    
    # Create colored trajectory based on phases
    colors = ['#f0f0f0', '#404040']
    cmap = ListedColormap(colors)
    
    # Main trajectory heatmap
    im = ax1.imshow(trajectory_matrix, cmap=cmap, aspect='auto', interpolation='nearest', origin='upper')
    
    # Add vertical line at attractor entry point
    if result['converged'] and result['steps_to_attractor'] > 0:
        if result['converged'] and result['steps_to_attractor'] > 0:
            rect = Rectangle((-0.5, result['steps_to_attractor']-1.5), n_genes, 1, 
                            linewidth=4, edgecolor='red', facecolor='none', alpha=0.8)
            ax1.add_patch(rect)
    
    # Set labels and ticks
    ax1.set_xticks(range(n_genes))
    ax1.set_xticklabels(genes, rotation=45, ha='right')
    ax1.set_yticks(range(0, n_steps, max(1, n_steps//10)))
    ax1.set_yticklabels(range(0, n_steps, max(1, n_steps//10)))
    ax1.set_xlabel('Genes')
    ax1.set_ylabel('Time Steps')
    ax1.set_title('Boolean Network Trajectory to Attractor')
    
    # Add grid
    ax1.set_xticks(np.arange(-0.5, n_genes, 1), minor=True)
    ax1.set_yticks(np.arange(-0.5, n_steps, 1), minor=True)
    ax1.grid(which='minor', color='white', linestyle='-', linewidth=0.5)
    
    # Create legend for main plot
    legend_elements = [
        mpatches.Patch(color='#f0f0f0', label='Inactive'),
        mpatches.Patch(color='#404040', label='Active')
    ]
    
    if result['converged']:
        att_info = attractors_dict[result['target_attractor_id']]
        legend_elements.append(
            mpatches.Patch(color='red', alpha=0.8, 
                          label=f"Attractor {result['target_attractor_id']} ({att_info['type']})")
        )
    
    fig.legend(handles=legend_elements, loc='upper right', bbox_to_anchor=(0.98, 0.98))
    
    # Save plot
    plt.savefig(f"{output_path}_trajectory.png", dpi=300, bbox_inches='tight')
    plt.savefig(f"{output_path}_trajectory.svg", bbox_inches='tight')
    plt.close()
    
    log_message(f"Trajectory visualization saved as {output_path}_trajectory.png and .svg", verbose)


def path_to_attractor_analysis(args):
    """
    Main function for path to attractor analysis
    
    Args:
        args: Parsed command line arguments
    """
    # Validate input files
    if not os.path.exists(args.attractors_file):
        print(f"ERROR: Attractors file not found: {args.attractors_file}", file=sys.stderr)
        sys.exit(1)
    
    if not os.path.exists(args.rules_file):
        print(f"ERROR: Rules file not found: {args.rules_file}", file=sys.stderr)
        sys.exit(1)
    
    # Create output directory
    if args.output_dir:
        output_dir = args.output_dir
    else:
        output_dir = os.path.dirname(args.attractors_file)
    
    os.makedirs(output_dir, exist_ok=True)
    
    try:
        # Read attractors and rules
        df_attractors, gene_cols, attractors_dict = read_attractors_file(args.attractors_file, args.verbose)
        gene_rules = read_rules_file(args.rules_file, args.verbose)
        
        # Parse initial state
        initial_state = parse_initial_state(args.initial_state, gene_cols, args.verbose)
        
        # Simulate trajectory
        result = simulate_trajectory_to_attractor(
            initial_state, gene_rules, gene_cols, attractors_dict, 
            args.max_steps, args.verbose
        )
        
        # Create output base path
        if args.output_base:
            output_base = os.path.join(output_dir, args.output_base)
        else:
            output_base = os.path.join(output_dir, "trajectory")
        
        # Save results
        trajectory_file = f"{args.output_base or 'trajectory'}.tsv"
        save_trajectory_tsv(result['trajectory'], gene_cols, result, output_dir, trajectory_file, args.verbose)
        
        # Create visualization
        visualize_trajectory(result['trajectory'], gene_cols, result, attractors_dict, output_base, args.verbose)
        
        # Print summary
        print(f"\n{'='*60}")
        print("TRAJECTORY ANALYSIS COMPLETED")
        print('='*60)
        print(f"Initial state: {args.initial_state}")
        print(f"Steps to attractor: {result['steps_to_attractor']}")
        
        if result['converged']:
            att_info = attractors_dict[result['target_attractor_id']]
            print(f"Target attractor: {result['target_attractor_id']} ({att_info['type']})")
            print(f"Attractor basin size: {att_info['basin_size']} states ({att_info['basin_percentage']:.2f}%)")
            if result['found_at_step']:
                print(f"Entered at step: {result['found_at_step']} of cycle")
        else:
            print("Target attractor: Did not converge to known attractor")
        
        print(f"Trajectory length: {len(result['trajectory'])} states")
        print(f"Output files:")
        print(f"- {trajectory_file} (trajectory data)")
        print(f"- {os.path.basename(output_base)}_trajectory.png/svg (visualization)")
        print('='*60)
        
    except Exception as e:
        print(f"ERROR: {str(e)}", file=sys.stderr)
        if args.verbose:
            import traceback
            traceback.print_exc()
        sys.exit(1)


def main():
    """Main function with argument parsing"""
    parser = argparse.ArgumentParser(
        description='Simulate trajectories from initial states to attractors in Boolean networks',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 2.BNI3_Path_to_Attractors.py -a attractors.tsv -r selected_rules.tsv -s "1010110010110"
  python3 2.BNI3_Path_to_Attractors.py -a attractors.tsv -r selected_rules.tsv -s "ABF3,NRT2_1,TGA4" -v
  python3 2.BNI3_Path_to_Attractors.py -a attractors.tsv -r rules_by_gene.tsv -s "0000000000000" -o output/

Input Files:
  Preferred: selected_rules.tsv (generated by 1.BNI3_Attractors.py)
  Legacy:    full rules table with Position column (slower, uses Position=1)

Initial State Formats:
  Binary string    : "1010110010110" (length must match number of genes)
  Gene list        : "ABF3,NRT2_1,TGA4" (comma-separated active gene names)

Output:
  - TSV file with complete trajectory (step, gene states, phase)
  - PNG/SVG visualization showing gene activity over time
  - Summary information about convergence and target attractor

Notes:
  - Requires attractors.tsv from 1.BNI3_Attractors.py
  - Requires rules file from ../2.Rules_Inference/2.BNI3_Analyze_results.py  
  - Uses same rule selection criteria as 1.BNI3_Attractors.py
  - Simulation stops when known attractor is reached or max steps exceeded
  - Detects cycles that don't match known attractors
        """
    )
    
    # Required parameters
    required = parser.add_argument_group('Required parameters')
    required.add_argument('-a', '--attractors_file', type=str, required=True,
                         help='Input attractors TSV file (from 1.BNI3_Attractors.py)')
    required.add_argument('-s', '--initial_state', type=str, required=True,
                         help='Initial state as binary string or comma-separated gene list')
    required.add_argument('-r', '--rules_file', type=str, required=True,
                     help='Input rules file: selected_rules.tsv (from 1.BNI3_Attractors.py) or full rules table')
    
    # Optional parameters
    optional = parser.add_argument_group('Optional parameters')
    optional.add_argument('-o', '--output_dir', type=str, default=None,
                         help='Output directory (default: same as attractors file)')
    optional.add_argument('-ob', '--output_base', type=str, default=None,
                         help='Base name for output files (default: trajectory)')
    optional.add_argument('--max-steps', type=int, default=1000,
                         help='Maximum simulation steps (default: 1000)')
    optional.add_argument('-v', '--verbose', action='store_true',
                         help='Show detailed processing information')
    
    parser.add_argument('--version', action='version', version='Boolean Network Path to Attractor v1.0')
    
    args = parser.parse_args()
    
    # Validate input files exist
    if not os.path.exists(args.attractors_file):
        print(f"ERROR: Attractors file '{args.attractors_file}' does not exist.", file=sys.stderr)
        sys.exit(1)
    
    if not os.path.exists(args.rules_file):
        print(f"ERROR: Rules file '{args.rules_file}' does not exist.", file=sys.stderr)
        sys.exit(1)
    
    # Run analysis
    try:
        path_to_attractor_analysis(args)
    except KeyboardInterrupt:
        print("\nProcess interrupted by user.", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()